/**
 * PR summary generator: assembles a ready-to-use pull request description
 * from data the harness already has — session decisions/notes, diff stats,
 * and the latest gate report. Output is designed for
 * `gh pr create --body-file <(harness pr-summary)`.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import type { HarnessConfig } from "../config/schema.js";
import { getActiveSession, listSessions, loadEvents } from "../session/store.js";
import type { RunReport, Session, SessionEvent } from "../types.js";

function git(root: string, args: string[]): string {
  return execFileSync("git", args, { cwd: root, encoding: "utf8", maxBuffer: 10 * 1024 * 1024 });
}

function latestGateReport(root: string, config: HarnessConfig): RunReport | null {
  const dir = path.join(root, config.report.dir);
  try {
    const latest = fs
      .readdirSync(dir)
      .filter((f) => f.endsWith("-gate.json"))
      .sort()
      .pop();
    if (!latest) return null;
    return JSON.parse(fs.readFileSync(path.join(dir, latest), "utf8")) as RunReport;
  } catch {
    return null;
  }
}

function relevantSession(root: string): { session: Session; events: SessionEvent[] } | null {
  const session = getActiveSession(root) ?? listSessions(root).at(-1) ?? null;
  if (!session) return null;
  return { session, events: loadEvents(root, session.id) };
}

export function buildPrSummary(root: string, config: HarnessConfig, baseRef?: string): string {
  const range = baseRef ? [`${baseRef}...HEAD`] : ["HEAD"];

  let diffStat = "";
  let branch = "";
  try {
    branch = git(root, ["rev-parse", "--abbrev-ref", "HEAD"]).trim();
    diffStat = git(root, ["diff", "--stat", ...range]).trim();
  } catch {
    // not a git repo — summary still works from session data alone
  }

  const ctx = relevantSession(root);
  const report = latestGateReport(root, config);

  const lines: string[] = [];
  lines.push(`## Summary`);
  lines.push("");
  lines.push(ctx ? `${ctx.session.title} (${ctx.session.id})` : config.project.name);
  if (ctx) {
    lines.push("");
    lines.push(`Agents involved: ${ctx.session.agents.join(", ")}`);
  }
  lines.push("");

  if (diffStat) {
    lines.push("## Changes");
    lines.push("");
    lines.push("```");
    // Keep the stat block reviewable even on big branches.
    const statLines = diffStat.split("\n");
    lines.push(...statLines.slice(0, 40));
    if (statLines.length > 40) lines.push(`… and ${statLines.length - 40} more files`);
    lines.push("```");
    lines.push("");
  }

  if (ctx) {
    const decisions = ctx.events.filter((e) => e.kind === "decision");
    if (decisions.length > 0) {
      lines.push("## Design decisions");
      lines.push("");
      for (const d of decisions) lines.push(`- ${d.text} _(${d.agent})_`);
      lines.push("");
    }
    const notes = ctx.events.filter((e) => e.kind === "note");
    if (notes.length > 0) {
      lines.push("## Notes");
      lines.push("");
      for (const n of notes) lines.push(`- ${n.text} _(${n.agent})_`);
      lines.push("");
    }
  }

  lines.push("## Quality gates");
  lines.push("");
  if (report?.gates) {
    lines.push(`Latest run: ${report.passed ? "✅ passed" : "❌ failing"} (${report.generatedAt})`);
    lines.push("");
    lines.push("| Gate | Status | Detail |");
    lines.push("|------|--------|--------|");
    for (const g of report.gates) {
      lines.push(`| ${g.id} | ${g.status} | ${g.reason ?? ""} |`);
    }
  } else {
    lines.push("_No gate report found — run `harness gate run` before opening the PR._");
  }
  lines.push("");

  const risks = report?.unresolvedRisks ?? [];
  if (risks.length > 0) {
    lines.push("## Unresolved risks");
    lines.push("");
    for (const r of risks) lines.push(`- ${r}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `_Generated by dev-harness${branch ? ` from \`${branch}\`` : ""} at ${new Date().toISOString()}_`,
  );
  lines.push("");
  return lines.join("\n");
}
