/**
 * Marker-delimited managed blocks.
 *
 * The harness owns only the region between its markers inside files that
 * humans also edit (CLAUDE.md, AGENTS.md, ...). Everything outside the
 * markers is never touched, so re-running an integration safely updates
 * harness-managed content without clobbering hand-written sections.
 */
import fs from "node:fs";
import path from "node:path";
import { readIfExists } from "./fsutil.js";

export function beginMarker(id: string): string {
  return `<!-- dev-harness:${id} -->`;
}
export function endMarker(id: string): string {
  return `<!-- /dev-harness:${id} -->`;
}

export type UpsertAction = "created" | "appended" | "updated" | "unchanged";

/**
 * Insert or replace the managed block `id` in `filePath`.
 *
 * - file missing            -> create it with just the block
 * - both markers present    -> replace the region between them
 * - begin marker only       -> legacy append-once block (no end marker was
 *   written by older harness versions, always at EOF) -> replace to EOF
 * - no markers              -> append the block at EOF
 */
export function upsertMarkedBlock(filePath: string, id: string, body: string): UpsertAction {
  const begin = beginMarker(id);
  const end = endMarker(id);
  const block = `${begin}\n${body.trim()}\n${end}\n`;

  const existing = readIfExists(filePath);
  if (existing === null) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, block, "utf8");
    return "created";
  }

  const beginIdx = existing.indexOf(begin);
  if (beginIdx === -1) {
    fs.writeFileSync(filePath, existing.trimEnd() + "\n\n" + block, "utf8");
    return "appended";
  }

  const endIdx = existing.indexOf(end, beginIdx);
  const before = existing.slice(0, beginIdx);
  const after = endIdx === -1 ? "" : existing.slice(endIdx + end.length).replace(/^\n/, "");

  const next = before + block + after;
  if (next === existing) return "unchanged";
  fs.writeFileSync(filePath, next, "utf8");
  return "updated";
}

/**
 * Return the current body of the managed block `id` in `filePath`, or null if
 * the file or block is absent. The inverse of {@link upsertMarkedBlock}, used
 * to feed previously-recorded content back into a regeneration step.
 */
export function readMarkedBlock(filePath: string, id: string): string | null {
  const existing = readIfExists(filePath);
  if (existing === null) return null;
  const begin = beginMarker(id);
  const end = endMarker(id);
  const beginIdx = existing.indexOf(begin);
  if (beginIdx === -1) return null;
  const bodyStart = beginIdx + begin.length;
  const endIdx = existing.indexOf(end, bodyStart);
  return existing.slice(bodyStart, endIdx === -1 ? undefined : endIdx).trim();
}

/** Header line for files the harness fully owns (skills, slash commands, generated docs). */
export function generatedFileHeader(command: string): string {
  return `<!-- AUTO-GENERATED by \`${command}\` — edit harness.yaml / project_profile.json instead, this file is overwritten on sync -->`;
}

export function isGeneratedFile(content: string): boolean {
  return content.includes("AUTO-GENERATED by `harness");
}
