/**
 * Persist learn results.
 *
 * - contextRules → a managed block in CLAUDE.md (`dev-harness:learn`), so the
 *   guidance is loaded into every future Claude Code session automatically.
 * - lessons → project_profile.json notes, mirroring `harness session
 *   summarize`, so they also flow into `harness context` / the skill.
 *
 * Only the managed block is owned by the harness; the rest of CLAUDE.md is
 * never touched (see core/markers).
 */
import path from "node:path";
import { loadProfile, PROFILE_PATH } from "../analyze/analyzer.js";
import { writeJson } from "../core/fsutil.js";
import { upsertMarkedBlock } from "../core/markers.js";
import type { LearnAnalysis } from "./types.js";

export const LEARN_MARKER_ID = "learn";

/** Render the managed-block markdown for the recorded rules. */
export function renderLearnBlock(analysis: LearnAnalysis, date: string): string {
  const lines = [
    "## Learned patterns",
    `*Auto-generated by \`harness learn\` on ${date} — re-run to refresh; edit outside the markers to keep changes.*`,
    "",
  ];
  for (const rule of analysis.contextRules) {
    lines.push(`### ${rule.section}`);
    if (rule.estimatedTokensSaved) lines.push(`*~${rule.estimatedTokensSaved.toLocaleString()} tokens/session saved*`);
    lines.push(rule.content.trim(), "");
  }
  return lines.join("\n").trim();
}

/** Write the analysis to CLAUDE.md and the project profile. Returns files changed. */
export function writeLearnResults(root: string, analysis: LearnAnalysis, date: string): string[] {
  const written: string[] = [];

  if (analysis.contextRules.length > 0) {
    const claudeMd = path.join(root, "CLAUDE.md");
    const action = upsertMarkedBlock(claudeMd, LEARN_MARKER_ID, renderLearnBlock(analysis, date));
    if (action !== "unchanged") written.push("CLAUDE.md");
  }

  if (analysis.lessons.length > 0) {
    const profile = loadProfile(root);
    if (profile) {
      let added = false;
      for (const lesson of analysis.lessons) {
        const note = `[learn] ${lesson}`;
        if (!profile.notes.includes(note)) {
          profile.notes.push(note);
          added = true;
        }
      }
      if (added) {
        writeJson(path.join(root, PROFILE_PATH), profile);
        written.push(PROFILE_PATH);
      }
    }
  }

  return written;
}
